### PR TITLE
release 1.1102

### PR DESCRIPTION
**Pull request by ollyg**
In response to this ticket:
https://rt.cpan.org/Ticket/Display.html?id=108812
I issued a point release to fix the manifest.
Apologies if this was the wrong thing to do.

### CODE REVIEW

**Comment by ollyg** [comment]
Oh, I couldn't release to CPAN as I don't have co-maint permissions. If you are happy to do so, then you can give them to me. I'll try to be responsible :-)

**Comment by jhthorsen** [comment]
No need to be sorry at all 😄 

I'll give you commit bit on github and pause.

Would you mind also updating the issue tracker to github?

**Comment by ollyg** [comment]
OK done :)

**Comment by jhthorsen** [comment]
Thanks! 👍

**Pull request merged**
